version: 0.0
os: linux
files:
  - source: /scripts/pull-docker-images.sh
    destination: /home/ubuntu/

hooks:
  AfterInstall:
    - location: /home/ubuntu/pull-docker-images.sh
      timeout: 300
      runas: root
