version: 0.0
os: linux

hooks:
  ApplicationStop:
    # Stop running containers before starting new ones
    - location: scripts/stop-containers.sh
      timeout: 300
      runas: root

  ApplicationStart:
    # Start or restart your Docker containers with the new images
    - location: scripts/start-containers.sh
      timeout: 300
      runas: root
