linters:
  enable:
    - revive
    - errcheck
    - staticcheck
    - gofmt
    - goimports
    - ineffassign
    - typecheck
    - unused
    - misspell
    - gocyclo

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
run:
  timeout: 5m
